### ISSUE TITLE
Error at running : poetry run python -m pycarla <mid>

### ISSUE THREAD

**Issue by dfaud** [LIMUNIMI/pycarla#5]
Hi,
After launching this syntax :
poetry run python -m pycarla k12.mid

I m getting this errors :
![image](https://user-images.githubusercontent.com/10832798/208245363-b0638b7c-f484-4e0b-bfc7-73e987480576.png)

note : k12.mid exist in the \pycarla

Thank !

**Comment by 00sapo** [comment]
Hi, as explained in the [documentation](https://pycarla.readthedocs.io/en/latest/Installation.html#development-setup), that command is reserved for testing and developing this module. Are you willing to add/modify features? If so, please open an ad hoc issue and I will be happy to discuss this with you.

Otherwise, you should look at the [usage](https://pycarla.readthedocs.io/en/latest/Examples.html) section in the docs. If you really really want to use that command, then it's just running `pycarla/__main__.py` in this module, so you also need to change that script correctly. 

The error you get is connected with the Carla preset path that is hard-coded in the script (which was ok for testing until now, since I am the only contributor to this project, until now).

Btw, keep in mind that I have never tested pycarla in windows. It would be helpful if you detail how you installed everything (jack, carla) in respect to the docs.

Thank you!

federico
